{% set name = "decifer" %}
{% set version = "1.1.3" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://github.com/raphael-group/{{ name }}/archive/v{{ version }}.zip
  sha256: 68298f7907379c0d5149dc35b946244d63502a06223106a352062943c6f10fca

build:
  skip: True  # [py3k]
  number: 0
  entry_points:
    - decifer = decifer.decifer:main
    - fitbeta = decifer.generator:main

requirements:
  build:
    - make
    - cmake >=3.9
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - lemon >= 1.3.1
    - boost-cpp
  run:
    - lemon >= 1.3.1
    - python
    - numpy >=1.16.1
    - scipy >=1.2.1
    - pandas 
    - seaborn >=0.7.1

test:
  commands:
    - generatestatetrees
    - mergestatetrees
    - decifer -h
    - fitbeta -h

about:
  home: https://github.com/raphael-group/decifer
  license: BSD-3
  summary: "DeCiFer simultaneously selects mutation multiplicities and clusters SNVs by their corresponding descendant cell fractions (DCF)"
  description: |
    DeCiFer is an algorithm that simultaneously selects mutation multiplicities and clusters SNVs by their corresponding descendant cell fractions (DCF), a statistic that quantifies the proportion of cells which acquired the SNV or whose ancestors acquired the SNV. DCF is related to the commonly used cancer cell fraction (CCF) but further accounts for SNVs which are lost due to deleterious somatic copy-number aberrations (CNAs), identifying clusters of SNVs which occur in the same phylogenetic branch of tumour evolution.

